using System;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Text;
using HorizonRadio.Core.History;
using ShadUI;

namespace HorizonRadio.UI.Services;

/// <summary>
/// Opens a pre-filled GitHub "new issue" draft for a song the metadata pipeline couldn't
/// identify, so a user can report a matching gap in one click. Builds a title + markdown body
/// with the reproducible details (what the stream called the song, the parses we considered,
/// when it played, the app version) and hands the URL to the OS browser — it only drafts the
/// issue; the user still reviews and submits it.
/// </summary>
public static class GitHubReport
{
    private const string NewIssueUrl = "https://github.com/dhkatz/HorizonRadio/issues/new";

    public static void OpenIssueDraft(PlayHistoryEntry entry, ToastManager? toasts = null)
    {
        try
        {
            var url = $"{NewIssueUrl}?title={Uri.EscapeDataString(BuildTitle(entry))}" +
                      $"&body={Uri.EscapeDataString(BuildBody(entry))}";
            Process.Start(new ProcessStartInfo(url) { UseShellExecute = true });
        }
        catch (Exception ex)
        {
            toasts?.CreateToast("Couldn't open the report")
                .WithContent(ex.Message).WithDelay(6).DismissOnClick().ShowError();
        }
    }

    private static string BuildTitle(PlayHistoryEntry e)
    {
        var song = string.IsNullOrWhiteSpace(e.Artist) ? e.Title : $"{e.Artist} – {e.Title}";
        return $"Metadata: couldn't identify \"{song}\"";
    }

    private static string BuildBody(PlayHistoryEntry e)
    {
        // Plain string concatenation (not AppendLine's interpolated-handler overload) so the
        // report text is locale-independent — these are markdown lines, not formatted numbers.
        var sb = new StringBuilder();
        void Line(string text = "") => sb.Append(text).Append('\n');

        Line("> Reported from Horizon Radio's play history. The app couldn't confidently");
        Line("> match this song to a catalog, so its metadata may be wrong.");
        Line();
        Line("- **Source:** " + e.SourceDisplay);
        Line("- **Displayed title:** " + Or(e.Title));
        Line("- **Displayed artist:** " + Or(e.Artist));
        if (!string.IsNullOrWhiteSpace(e.Album)) Line("- **Album:** " + e.Album);
        Line("- **Played at:** " + e.PlayedAt.ToLocalTime().ToString("f", CultureInfo.CurrentCulture));
        Line("- **App version:** " + AppVersion());

        if (e.Candidates.Count > 0)
        {
            Line();
            Line("**Alternative parses considered:**");
            foreach (var c in e.Candidates)
                Line(string.IsNullOrWhiteSpace(c.Artist) ? "- " + c.Title : $"- {c.Artist} – {c.Title}");
        }

        Line();
        Line("**What should it be?** (artist / title / album, or a link to the right track)");
        Line();
        Line("<!-- generated by Horizon Radio history report -->");
        return sb.ToString();
    }

    private static string Or(string? value) => string.IsNullOrWhiteSpace(value) ? "_(blank)_" : value;

    private static string AppVersion()
    {
        var asm = Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly();
        return asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
            ?? asm.GetName().Version?.ToString()
            ?? "unknown";
    }
}
